#!/usr/bin/env bash
# Script that install nginx server and write to the root.
sudo apt update -y
sudo apt install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
