#!/usr/bin/env bash
# Script that install nginx server and write to the root.
sudo apt update -y
sudo apt install nginx -y
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
