#!/usr/bin/env bash
# Script that install nginx server and write content to the root
sudo apt update && upgrade
sudo apt install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
