#!/usr/bin/env bash
# Script that install nginx server and write to the root.
sudo apt update -y
sudo apt install nginx -y
sudo echo "Holberton School" > /var/www/html/index.html.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
